# Builds the binaries which can be uploaded to the Microsoft/Google store
name: Build SilentNotes binaries

on:
  workflow_dispatch:
    inputs:
      publish-release:
        type: boolean
        default: true
        description: Publish new release on GitHub

env:
  Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj
  Target_Framework_Android: net8.0-android
  Target_Framework_Windows: net8.0-windows10.0.19041.0

jobs:
  ##############################################################################
  # Android multi platform apk (armeabi-v7;arm64-v8a)
  # Platforms are taken from the csproj, to build one apk with multiple platforms
  ##############################################################################
  job_build_android:
    strategy:
      matrix:
        configuration: [Release]
  
    runs-on: windows-latest

    env:
      Keystore_Path: src\SilentNotes.Blazor\silentnotes.keystore # Same directory as csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Install MAUI
      run: dotnet workload install maui-android --ignore-failed-sources

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the keystore file
      run: |
        echo "${{ secrets.SILENTNOTESANDROIDKEYSTORE }}" > "${{ env.Keystore_Path }}.asc"
        gpg -d --quiet --batch --yes --passphrase="${{ env.KeystoreGpgPassword }}" --output "${{ env.Keystore_Path }}" "${{ env.Keystore_Path }}.asc"
      env:
        KeystoreGpgPassword: ${{ secrets.SILENTNOTESANDROIDKEYSTOREGPGPASSWORD }}

    # Build application
    # The keystore location seems to be relative to the csproj file, so we placed it in the same directory pass only the filename
    - name: Build application
      run: dotnet publish "${{ env.Project_Path }}" -c ${{ env.Configuration }} -f ${{ env.Target_Framework_Android }} -o ".\bin" -p:AndroidPackageFormats=apk -p:PublishTrimmed=true -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=silentnotes.keystore -p:AndroidSigningKeyAlias=androidmartinstoeckli -p:AndroidSigningKeyPass=${{ env.KeystorePassword }} -p:AndroidSigningStorePass=${{ env.KeystorePassword }}
      env:
        Configuration: ${{ matrix.configuration }}
        KeystorePassword: ${{ secrets.SILENTNOTESANDROIDKEYSTOREPASSWORD }}
        
    - name: Remove the keystore
      run: Remove-Item -path "${{ env.Keystore_Path }}"
    - name: Remove encoded keystore
      run: Remove-Item -path "${{ env.Keystore_Path }}.asc"

    - name: Collect apk files
      run: |
        $apks = Get-ChildItem -Path .\bin\* -Filter *Signed.apk -Recurse -File
        New-Item -Path ".\artifacts" -ItemType "directory"
        Move-Item -Path $apks[0].FullName -Destination ".\artifacts\silentnotes.apk"

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: silentnotes_binaries
        path: .\artifacts

  ##############################################################################
  # Android additional platforms
  ##############################################################################
  job_build_android_additional_platform:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
  
    runs-on: windows-latest

    env:
      Keystore_Path: src\SilentNotes.Blazor\silentnotes.keystore # Same directory as csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Install MAUI
      run: dotnet workload install maui-android --ignore-failed-sources

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the keystore file
      run: |
        echo "${{ secrets.SILENTNOTESANDROIDKEYSTORE }}" > "${{ env.Keystore_Path }}.asc"
        gpg -d --quiet --batch --yes --passphrase="${{ env.KeystoreGpgPassword }}" --output "${{ env.Keystore_Path }}" "${{ env.Keystore_Path }}.asc"
      env:
        KeystoreGpgPassword: ${{ secrets.SILENTNOTESANDROIDKEYSTOREGPGPASSWORD }}

    # Build application
    # The keystore location seems to be relative to the csproj file, so we placed it in the same directory pass only the filename
    - name: Build application
      run: dotnet publish "${{ env.Project_Path }}" -c ${{ env.Configuration }} -f ${{ env.Target_Framework_Android }} -r android-${{ env.Platform }} -o ".\bin" -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=silentnotes.keystore -p:AndroidSigningKeyAlias=androidmartinstoeckli -p:AndroidSigningKeyPass=${{ env.KeystorePassword }} -p:AndroidSigningStorePass=${{ env.KeystorePassword }}
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
        KeystorePassword: ${{ secrets.SILENTNOTESANDROIDKEYSTOREPASSWORD }}
        
    - name: Remove the keystore
      run: Remove-Item -path "${{ env.Keystore_Path }}"
    - name: Remove encoded keystore
      run: Remove-Item -path "${{ env.Keystore_Path }}.asc"

    - name: Collect apk files
      run: |
        $apks = Get-ChildItem -Path .\bin\* -Filter *Signed.apk -Recurse -File
        New-Item -Path ".\artifacts" -ItemType "directory"
        Move-Item -Path $apks[0].FullName -Destination ".\artifacts\silentnotes_${{ env.Platform }}.apk"
      env:
        Platform: ${{ matrix.platform }}

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: silentnotes_binaries
        path: .\artifacts

  ##############################################################################
  # Windows
  ##############################################################################
  job_build_windows:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x86,x64,arm64]
  
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install MAUI
      run: dotnet workload install maui-windows --ignore-failed-sources

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the pfx
      run: |
        echo "${{ secrets.SILENTNOTESPFX }}" > SilentNotes.pfx.asc
        certutil -decode SilentNotes.pfx.asc SilentNotes.pfx
    - name: Remove decoded pfx
      run: Remove-Item -path SilentNotes.pfx.asc
    - name: Add cert to store
      run: certutil -user -q -p ${{ secrets.SILENTNOTESPFXPASSWORD }} -importpfx SilentNotes.pfx NoRoot

    # Build application
    - name: Build application
      run: dotnet publish "${{ env.Project_Path }}" -c ${{ env.Configuration }} -f ${{ env.Target_Framework_Windows }} -a ${{ env.Platform }} -o ".\bin" --no-self-contained -p:RuntimeIdentifierOverride=win10-${{ env.Platform }} -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=true -p:PackageCertificateThumbprint="${{ secrets.SILENTNOTESPFXTHUMBPRINT }}"
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
        BuildMode: StoreOnly
        
    # Remove the pfx
    - name: Remove the pfx
      run: Remove-Item -path SilentNotes.pfx

    - name: Collect apk files
      run: |
        $apks = Get-ChildItem -Path .\bin\* -Filter SilentNotes*.msix -Recurse -File
        New-Item -Path ".\windows" -ItemType "directory"
        Move-Item -Path $apks[0].FullName -Destination ".\windows\silentnotes_${{ env.Platform }}.msix"
      env:
        Platform: ${{ matrix.platform }}

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: silentnotes_binaries
        path: .\windows

  ##############################################################################
  # Windows packaging
  # Package all msix to a single msixbundle for uploading to the Microsoft store
  ##############################################################################
  job_package:
    needs: job_build_windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Read verion from csproj
    - name: Read version from csproj
      id: csproj_version
      uses: mavrosxristoforos/get-xml-info@1.2.1
      with:
        xml-file: "${{ env.Project_Path }}"
        xpath: //PropertyGroup/ApplicationDisplayVersion
    - name: Log version
      run: |
        echo "version=${{ steps.csproj_version.outputs.info }}"

    - name: Download msix files
      uses: actions/download-artifact@v3
      with:
        name: silentnotes_binaries
        path: downloaddirectory

    - name: Collect msix files
      run: |
        New-Item -Path ".\msixdirectory" -ItemType "directory"
        Move-Item -Path .\downloaddirectory\*.msix -Destination .\msixdirectory

    - name: Make msixbundle
      id: bundler
      uses: LanceMcCarthy/Action-MsixBundler@v1.0.0
      with:
        msix-folder: "msixdirectory"
        msixbundle-filepath: "silentnotes.msixbundle"
        msixbundle-version: "${{ steps.csproj_version.outputs.info }}.0"
      
    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: silentnotes_binaries
        path: .\**\*.msixbundle
        retention-days: 1

  ##############################################################################
  # Publish release on Github
  ##############################################################################
  job_publish_release:
    needs: [job_build_android, job_build_android_additional_platform]
    if: ${{ inputs.publish-release }}

    runs-on: windows-latest

    env:
      Solution_Name: SilentNotes.sln
      Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj
      Android_Manifest: src\SilentNotes.Blazor\Platforms\Android\AndroidManifest.xml

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Read version from csproj
    - name: Read version from csproj
      id: csproj_version
      uses: mavrosxristoforos/get-xml-info@1.2.1
      with:
        xml-file: "${{ env.Project_Path }}"
        xpath: //PropertyGroup/ApplicationDisplayVersion

    # Read increasing android version
    - name: Read version for android
      id: android_version
      uses: mavrosxristoforos/get-xml-info@1.2.1
      with:
        xml-file: "${{ env.Project_Path }}"
        xpath: //PropertyGroup/ApplicationVersion

    - name: Download files for publishing
      uses: actions/download-artifact@v3
      with:
        name: silentnotes_binaries
        path: downloaddirectory

    - name: Collect files for publishing
      run: |
        New-Item -Path ".\publish" -ItemType "directory"
        Move-Item -Path .\downloaddirectory\*.apk -Destination .\publish

    - name: release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        draft: true
        prerelease: true
        name: ${{ env.Version_Title }}
        tag_name: ${{ env.Tag }}
        body_path: ${{ env.Change_Log }}
        files: |
          ./publish/*.apk
      env:
        GITHUB_TOKEN: ${{ github.token }}
        Version_Title: "Version ${{ steps.csproj_version.outputs.info }} CI test"
        Tag: "v${{ steps.csproj_version.outputs.info }}"
        Change_Log: "./fastlane/metadata/android/en-US/changelogs/64.txt" 
#        Change_Log: "./fastlane/metadata/android/en-US/changelogs/${{ steps.android_version.outputs.info }}.txt" 
