# Builds the msixbundle file which can be uploaded to the Google Play store
name: SilentNotes Build for Android

on: workflow_dispatch

env:
  Solution_Name: SilentNotes.sln
  Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj
  Keystore_Path: src\SilentNotes.Blazor\silentnotes.keystore
  Target_Framework: net7.0-android33.0

jobs:
  job_build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [arm64,x64]
  
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Install MAUI
      run: dotnet workload install maui-android --ignore-failed-sources

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the keystore file
      run: |
        echo "${{ secrets.SILENTNOTESANDROIDKEYSTORE }}" > "${{ env.Keystore_Path }}.asc"
        gpg -d --quiet --batch --yes --passphrase="${{ env.KeystoreGpgPassword }}" --output "${{ env.Keystore_Path }}" "${{ env.Keystore_Path }}.asc"
      env:
        KeystoreGpgPassword: ${{ secrets.SILENTNOTESANDROIDKEYSTOREGPGPASSWORD }}

    # Build application
    # The keystore location seems to be relative to the csproj file, so we placed it in the same directory pass only the filename
    - name: Build application
      run: dotnet publish "${{ env.Project_Path }}" -c ${{ env.Configuration }} -f ${{ env.Target_Framework }} -r android-${{ env.Platform }} -o ".\bin" -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=silentnotes.keystore -p:AndroidSigningKeyAlias=androidmartinstoeckli -p:AndroidSigningKeyPass=${{ env.KeystorePassword }} -p:AndroidSigningStorePass=${{ env.KeystorePassword }}
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
        KeystorePassword: ${{ secrets.SILENTNOTESANDROIDKEYSTOREPASSWORD }}
        
    - name: Remove the keystore
      run: Remove-Item -path "${{ env.Keystore_Path }}"
    - name: Remove encoded keystore
      run: Remove-Item -path "${{ env.Keystore_Path }}.asc"

    - name: Collect apk files
      run: |
        Copy-Item -Path .\bin -Filter *Signed.apk -Destination ".\android\SilentNotes_${{ env.Platform }}.apk" -Recurse -Container:$false
      env:
        Platform: ${{ matrix.platform }}

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: download
        path: .\android
