# Builds the msixbundle file which can be uploaded to the Google Play store
name: SilentNotes Build for Android

on: workflow_dispatch

env:
  Solution_Name: SilentNotes.sln
  Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj
  Target_Framework: net7.0-android33.0

jobs:
  job_build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [android-arm64]
  
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install MAUI
      run: dotnet workload install maui-android --ignore-failed-sources

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    # - name: Restore the application
    #   run: msbuild $env:Project_Path /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
    #   env:
    #     Configuration: ${{ matrix.configuration }}
    #     RuntimeIdentifier: win-${{ matrix.platform }}

    # Execute unit tests
    # - name: Execute unit tests (SilentNotes)
    #   run: dotnet test src\Tests\SilentNotesTest\SilentNotesTest.csproj
    # - name: Execute unit tests (VanillaCloudStorageClient)
    #   run: dotnet test src\Tests\VanillaCloudStorageClientTest\VanillaCloudStorageClientTest.csproj

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the keystore file
      run: |
        echo "${{ secrets.SILENTNOTESANDROIDKEYSTORE }}" > SilentNotes.keystore.asc
        gpg -d --passphrase "${{ secrets.SILENTNOTESANDROIDKEYSTOREGPGPASSWORD }}" --batch SilentNotes.keystore.asc > SilentNotes.keystore
    - name: Remove encoded keystore
      run: Remove-Item -path SilentNotes.keystore.asc

    # Build application
    - name: Build application
      run: dotnet publish "${{ env.Project_Path }}" -c ${{ env.Configuration }} -f ${{ env.Target_Framework }} -a ${{ env.Platform }} -o ".\bin" -p:AndroidKeyStore=True -p:AndroidSigningKeyStore="SilentNotes.keystore" -p:AndroidSigningStorePass="${{ secrets.SILENTNOTESANDROIDKEYSTOREPASSWORD }}"
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
        
    - name: Remove the keystore
      run: Remove-Item -path SilentNotes.keystore

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: msix-files
        path: |
          .\**\*.apk
          .\**\*.aab
          
