# Builds the msixbundle file which can be uploaded to the Google Play store
name: SilentNotes Build for Android

on: workflow_dispatch

env:
  Solution_Name: SilentNotes.sln
  Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj
  Target_Framework: net7.0-android33.0

jobs:
  job_build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [arm64]
  
    runs-on: windows-latest

    env:
      Keystore_Filename: ./androidmartinstoeckli.keystore
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Install MAUI
      run: dotnet workload install maui-android --ignore-failed-sources

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the keystore file
      run: |
        echo "${{ secrets.SILENTNOTESANDROIDKEYSTORE }}" > ${{ env.Keystore_Filename }}.asc
        gpg -d --passphrase "${{ secrets.SILENTNOTESANDROIDKEYSTOREGPGPASSWORD }}" --batch ${{ env.Keystore_Filename }}.asc > ${{ env.Keystore_Filename }}
    - name: Remove encoded keystore
      run: Remove-Item -path ${{ env.Keystore_Filename }}.asc
     
    # Build application
    - name: Build application
      run: dotnet publish "${{ env.Project_Path }}" -c ${{ env.Configuration }} -f ${{ env.Target_Framework }} -r android-${{ env.Platform }} -o ".\bin" -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=${{ env.Keystore_Filename }} -p:AndroidSigningKeyAlias=androidmartinstoeckli -p:AndroidSigningKeyPass="${{ secrets.SILENTNOTESANDROIDKEYSTOREPASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.SILENTNOTESANDROIDKEYSTOREPASSWORD }}"
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
        
    - name: Remove the keystore
      run: Remove-Item -path ${{ env.Keystore_Filename }}

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: msix-files
        path: |
          .\**\*.apk
          .\**\*.aab
          
