# Builds the msixbundle file which can be uploaded to the Microsoft store
name: SilentNotes Build for Windows

on: workflow_dispatch

env:
  Solution_Name: SilentNotes.sln
  Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj
  Target_Framework: net7.0-windows10.0.19041.0

jobs:
  job_build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x86,x64]
  
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install MAUI
      run: dotnet workload install maui-windows --ignore-failed-sources

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    # - name: Restore the application
    #   run: msbuild $env:Project_Path /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
    #   env:
    #     Configuration: ${{ matrix.configuration }}
    #     RuntimeIdentifier: win-${{ matrix.platform }}

    # Execute unit tests
    # - name: Execute unit tests (SilentNotes)
    #   run: dotnet test src\Tests\SilentNotesTest\SilentNotesTest.csproj
    # - name: Execute unit tests (VanillaCloudStorageClient)
    #   run: dotnet test src\Tests\VanillaCloudStorageClientTest\VanillaCloudStorageClientTest.csproj

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the pfx
      run: |
        echo "${{ secrets.SILENTNOTESPFX }}" > SilentNotes.pfx.asc
        certutil -decode SilentNotes.pfx.asc SilentNotes.pfx
    - name: Remove decoded pfx
      run: Remove-Item -path SilentNotes.pfx.asc
    - name: Add cert to store
      run: certutil -user -q -p ${{ secrets.SILENTNOTESPFXPASSWORD }} -importpfx SilentNotes.pfx NoRoot

    # Build application
    - name: Build application
      run: dotnet publish "${{ env.Project_Path }}" -c ${{ env.Configuration }} -f ${{ env.Target_Framework }} -a ${{ env.Platform }} -o ".\" --no-self-contained -p:RuntimeIdentifierOverride=win10-${{ env.Platform }} -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=true -p:PackageCertificateThumbprint="${{ secrets.SILENTNOTESPFXTHUMBPRINT }}"
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
        BuildMode: StoreOnly
        
    # Remove the pfx
    - name: Remove the pfx
      run: Remove-Item -path SilentNotes.pfx

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: msix-files
        path: .\**\AppPackages\**\SilentNotes*.msix

  job_package:
    needs: job_build
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Read verion from csproj
    - name: Read version
      id: csproj_version
      uses: mavrosxristoforos/get-xml-info@1.2.1
      with:
        xml-file: "${{ env.Project_Path }}"
        xpath: //PropertyGroup/ApplicationDisplayVersion

    - name: Download msix files
      uses: actions/download-artifact@v3
      with:
        name: msix-files
        path: msixdirectory

    - name: Make msixbundle
      id: bundler
      uses: LanceMcCarthy/Action-MsixBundler@v1.0.0
      with:
        msix-folder: "msixdirectory"
        msixbundle-filepath: "silentnotes.msixbundle"
        msixbundle-version: ${{ steps.csproj_version.outputs.info }}"
      
    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: msix-files
        path: .\**\*.msixbundle
        retention-days: 1
