# Builds the binaries which can be uploaded to the Microsoft/Google store
name: Build SilentNotes binaries

on: workflow_dispatch

env:
  Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj
  Target_Framework_Android: net7.0-android33.0
  Target_Framework_Windows: net7.0-windows10.0.19041.0

jobs:
  # Android
  job_build_android:
    strategy:
      matrix:
        configuration: [Release]
  
    runs-on: windows-latest

    env:
      Keystore_Path: src\SilentNotes.Blazor\silentnotes.keystore # Same directory as csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Install MAUI
      run: dotnet workload install maui-android --ignore-failed-sources

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the keystore file
      run: |
        echo "${{ secrets.SILENTNOTESANDROIDKEYSTORE }}" > "${{ env.Keystore_Path }}.asc"
        gpg -d --quiet --batch --yes --passphrase="${{ env.KeystoreGpgPassword }}" --output "${{ env.Keystore_Path }}" "${{ env.Keystore_Path }}.asc"
      env:
        KeystoreGpgPassword: ${{ secrets.SILENTNOTESANDROIDKEYSTOREGPGPASSWORD }}

    # Build application
    # The keystore location seems to be relative to the csproj file, so we placed it in the same directory pass only the filename
    - name: Build application
      run: dotnet publish "${{ env.Project_Path }}" -c ${{ env.Configuration }} -f ${{ env.Target_Framework_Android }} -o ".\bin" -p:AndroidPackageFormats=apk -p:PublishTrimmed=true -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=silentnotes.keystore -p:AndroidSigningKeyAlias=androidmartinstoeckli -p:AndroidSigningKeyPass=${{ env.KeystorePassword }} -p:AndroidSigningStorePass=${{ env.KeystorePassword }}
      env:
        Configuration: ${{ matrix.configuration }}
        KeystorePassword: ${{ secrets.SILENTNOTESANDROIDKEYSTOREPASSWORD }}
        
    - name: Remove the keystore
      run: Remove-Item -path "${{ env.Keystore_Path }}"
    - name: Remove encoded keystore
      run: Remove-Item -path "${{ env.Keystore_Path }}.asc"

    - name: Collect apk files
      run: |
        $apks = Get-ChildItem -Path .\bin\* -Filter *Signed.apk -Recurse -File
        New-Item -Path ".\android" -ItemType "directory"
        Move-Item -Path $apks[0].FullName -Destination ".\android\SilentNotes_arms.apk"

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: silentnotes_binaries
        path: .\android
