name: Test create release

on:
  workflow_dispatch:
    inputs:
      publish-release:
        type: boolean
        description: Publish new release on GitHub

jobs:
  job_create_release:
    if: ${{ inputs.publish-release }}

    strategy:
      matrix:
        configuration: [Release]
  
    runs-on: windows-latest

    env:
      Solution_Name: SilentNotes.sln
      Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj
      Android_Manifest: src\SilentNotes.Blazor\Platforms\Android\AndroidManifest.xml

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Read version from csproj
    - name: Read version from csproj
      id: csproj_version
      uses: mavrosxristoforos/get-xml-info@1.2.1
      with:
        xml-file: "${{ env.Project_Path }}"
        xpath: //PropertyGroup/ApplicationDisplayVersion

    # Read increasing android version
    - name: Read version for android
      id: android_version
      uses: mavrosxristoforos/get-xml-info@1.2.1
      with:
        xml-file: "${{ env.Project_Path }}"
        xpath: //PropertyGroup/ApplicationVersion

    # Upload artifacts
#    - name: Upload build artifacts
#      uses: actions/upload-artifact@v3.1.0
#      with:
#        name: msix-files
#        path: .\**\*.msix
#        retention-days: 1

    - name: write file 1
      run: echo hello > appendme.test

    - name: release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        draft: true
        prerelease: true
        overwrite: true
        name: ${{ env.Version_Title }}
        tag_name: ${{ env.Tag }}
        body_path: ${{ env.Change_Log }}
        files: |
          appendme.test
      env:
        GITHUB_TOKEN: ${{ github.token }}
        Version_Title: "Version ${{ steps.csproj_version.outputs.info }} CI test"
        Tag: "v${{ steps.csproj_version.outputs.info }}"
        Change_Log: "./fastlane/metadata/android/en-US/changelogs/64.txt" 
#        Change_Log: "./fastlane/metadata/android/en-US/changelogs/${{ steps.android_version.outputs.info }}.txt" 
