name: Test up and download

on: workflow_dispatch

jobs:
  job_build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x86, x64]
  
    runs-on: windows-latest

    env:
      Solution_Name: SilentNotes.sln
      Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj
      Target_Framework: net7.0-windows10.0.19041.0

    steps:
    - name: Create test dir
      run: |
        mkdir test
          
    - name: write file 1
      run: echo hello > test/world.msix
    - name: write file 2
      run: echo uhu > test/velo.msix
    
    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: msix-files
        path: .\**\*.msix
        retention-days: 1

  job_package:
    needs: job_build
    runs-on: windows-latest

    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: msix-files
        path: msixdirectory
      
    - name: Make msixbundle
      id: bundler
      uses: LanceMcCarthy/Action-MsixBundler@v1.0.0
      with:
        msix-folder: "msixdirectory"
        msixbundle-filepath: "silentnotes.msixbundle"
        msixbundle-version: "1.0.0.0"

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: msixbundle
        path: .\**\*.msixbundle
        retention-days: 1
