name: Test create release

on: workflow_dispatch

jobs:
  job_create_release:
    strategy:
      matrix:
        configuration: [Release]
  
    runs-on: windows-latest

    env:
      Solution_Name: SilentNotes.sln
      Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj
      Android_Manifest: src\SilentNotes.Blazor\Platforms\Android\AndroidManifest.xml

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Read verion from csproj
    - name: Read version from csproj
      id: csproj_version
      uses: mavrosxristoforos/get-xml-info@1.2.1
      with:
        xml-file: "${{ env.Project_Path }}"
        xpath: //PropertyGroup/ApplicationDisplayVersion
    - name: Log version
      run: |
        echo "version=${{ steps.csproj_version.outputs.info }}"

    # Upload artifacts
#    - name: Upload build artifacts
#      uses: actions/upload-artifact@v3.1.0
#      with:
#        name: msix-files
#        path: .\**\*.msix
#        retention-days: 1

    - name: release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        draft: true
        prerelease: true
        overwrite: true
        name: "Version ${{ steps.csproj_version.outputs.info }} CI test"
        tag_name: "${{ steps.csproj_version.outputs.info }}"
        body_path: .\fastlane\metadata\android\en-US\changelogs\64.txt
      env:
        GITHUB_TOKEN: ${{ github.token }}
