name: Test read csproj version

on: workflow_dispatch

jobs:
  job_build:
    strategy:
      matrix:
        configuration: [Release]
  
    runs-on: windows-latest

    env:
      Solution_Name: SilentNotes.sln
      Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get version
      id: csproj_version
      uses: KageKirin/get-csproj-version@v0
      with:
        file: "${{ env.Project_Path }}"
        xpath: //PropertyGroup/ApplicationDisplayVersion

    - name: publish on version change
      id: csproj_version_2
      uses: QwerMike/xpath-action@v1
      with:
        filename: "${{ env.Project_Path }}"
        expression: //PropertyGroup/ApplicationDisplayVersion

    - name: publish on version change
      id: csproj_version_3
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: "${{ env.Project_Path }}"
        xpath: //PropertyGroup/ApplicationDisplayVersion
          
    - name: logging
      run: |
        echo "version=${{ steps.csproj_version.outputs.version }}"
        echo "version2=${{ steps.csproj_version_2.outputs.result }}"
        echo "version3=${{ steps.csproj_version_3.outputs.info }}"
