name: Test read csproj version

on: workflow_dispatch

jobs:
  job_build:
    strategy:
      matrix:
        configuration: [Release]
  
    runs-on: windows-latest

    env:
      Solution_Name: SilentNotes.sln
      Project_Path: src\SilentNotes.Blazor\SilentNotes.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get version
      id: csproj_version
      uses: KageKirin/get-csproj-version@v0
      with:
        file: "${{ env.Project_Path }}"
        xpath: //PropertyGroup/ApplicationDisplayVersion

    - name: publish on version change
      id: csproj_version_2
      uses: chenryhabana205/dotnetgetversion@v6
      with:
        VERSION_FILE_PATH: "${{ env.Project_Path }}"
        VERSION_REGEX: ^\s*<ApplicationDisplayVersion>(.*)<\/ApplicationDisplayVersion>\s*$
          
    - name: logging
      run: |
        echo "version=${{ steps.csproj_version.outputs.version }}"
        echo "version=${{ steps.csproj_version_2.outputs.version }}"
